version: "3.9"

services:
  database:
    image: "postgres"
    restart: "always"
    environment:
      POSTGRES_PASSWORD: "mysecretpassword"
    volumes:
      - "data:/var/lib/postgresql/data"
  app:
    depends_on:
      - "database"
    build: .
    restart: "always"
    ports:
      - "$PORT:$PORT"
    volumes:
      - .:/app

volumes:
  data: {}
